ALTER SESSION SET "_oracle_script" = TRUE;

CREATE PROFILE PF_MyPharmacy LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
   
CREATE ROLE GUEST_MyPharmacy;

GRANT CREATE SESSION TO GUEST_MyPharmacy;
GRANT EXECUTE ON Register_User TO GUEST_MyPharmacy;
GRANT EXECUTE ON Find_Closest_Pharmacies TO GUEST_MyPharmacy;
GRANT EXECUTE ON SearchPharmacy TO GUEST_MyPharmacy;
GRANT SELECT ON T_DRUGS TO GUEST_MyPharmacy;
GRANT SELECT ON T_INSTITUTION TO GUEST_MyPharmacy;
GRANT SELECT ON Drug_Search_View TO GUEST_MyPharmacy;
GRANT SELECT ON Drug_Availability_View TO GUEST_MyPharmacy;

GRANT GUEST_MyPharmacy TO Guest;
-------------------------------
CREATE ROLE USER_MyPharmacy;

GRANT CREATE SESSION TO USER_MyPharmacy;
GRANT EXECUTE ON Update_User_Info TO USER_MyPharmacy;
GRANT EXECUTE ON Add_Review TO USER_MyPharmacy;
GRANT EXECUTE ON Add_To_Favorites TO USER_MyPharmacy;
GRANT EXECUTE ON Authenticate_User TO USER_MyPharmacy;
GRANT EXECUTE ON SearchPharmacy TO USER_MyPharmacy;
GRANT EXECUTE ON Add_Reservation TO USER_MyPharmacy;
GRANT EXECUTE ON Delete_Favorite TO USER_MyPharmacy;
GRANT EXECUTE ON Delete_Reservation TO USER_MyPharmacy;
GRANT EXECUTE ON Find_Closest_Pharmacies TO USER_MyPharmacy;
GRANT SELECT ON T_DRUGS TO USER_MyPharmacy;
GRANT SELECT ON T_USERS TO USER_MyPharmacy;
GRANT SELECT ON T_INSTITUTION TO USER_MyPharmacy;
GRANT SELECT ON Drug_Search_View TO USER_MyPharmacy;
GRANT SELECT ON Drug_Availability_View TO USER_MyPharmacy;
GRANT SELECT ON UserFavoritesView TO USER_MyPharmacy;
GRANT SELECT ON UserReservationView TO USER_MyPharmacy;

GRANT USER_MyPharmacy TO User_1;
----------------------------------
CREATE ROLE MANAGER_MyPharmacy;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE CLUSTER,
      CREATE PUBLIC SYNONYM,
      CREATE TRIGGER
 TO MANAGER_MyPharmacy;

GRANT MANAGER_MyPharmacy TO Programmer;
-----------------------------------------
CREATE ROLE PHARMACY_REPR_MyPharmacy;

GRANT CREATE SESSION TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Add_Availability TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Add_Drug TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Add_Pharmacy_Representative TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Delete_Availability TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Delete_Drug TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Get_User_Id TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Get_User_RoleId TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON SearchPharmacy TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Update_Pharmacy_Representative TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Update_Drug TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Update_Availability TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON UpdateReservationStatus TO PHARMACY_REPR_MyPharmacy;
GRANT EXECUTE ON Authenticate_User TO PHARMACY_REPR_MyPharmacy;
GRANT SELECT ON T_RESERVATION TO PHARMACY_REPR_MyPharmacy;
GRANT SELECT ON T_AVAILABILITY TO PHARMACY_REPR_MyPharmacy;
GRANT SELECT ON T_DRUGS TO PHARMACY_REPR_MyPharmacy;
GRANT SELECT ON T_INSTITUTION TO PHARMACY_REPR_MyPharmacy;

GRANT PHARMACY_REPR_MyPharmacy TO Predsavitel;