CREATE TABLESPACE TS_MyPharmacy
    DATAFILE 'C:\app\Tablespaces\TS_MyPharmacy.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE TS_MyPharmacy_TEMP
    TEMPFILE 'C:\app\Tablespaces\TS_MyPharmacy_TEMP.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLE Roles (
    RolId NUMBER PRIMARY KEY NOT NULL,
    Role_Name VARCHAR2(50) NOT NULL
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Users (
    UserId NUMBER PRIMARY KEY NOT NULL,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Middle_Name VARCHAR2(50) NOT NULL,
    Phone_Number VARCHAR2(20) NOT NULL,
    Email VARCHAR2(80) NOT NULL,
    RoleId NUMBER NOT NULL,
    Password VARCHAR2(20) NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(RolId) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Drugs (
    DrugID NUMBER PRIMARY KEY NOT NULL,
    Name VARCHAR2(100) NOT NULL,
    Manufacturer VARCHAR2(50) NOT NULL,
    Instruction VARCHAR2(1000) NOT NULL,
    Application_Features VARCHAR2(500) NOT NULL,
    Active_Substance VARCHAR2(100) NOT NULL,
    Indications VARCHAR2(500) NOT NULL,
    Contraindications VARCHAR2(500) NOT NULL,
    Dosage VARCHAR2(100) NOT NULL,
    Side_Effects VARCHAR2(500) NOT NULL
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Institutions (
    PharmacyID NUMBER PRIMARY KEY NOT NULL,
    Pharmacy_Name VARCHAR2(100) NOT NULL,
    Location SDO_GEOMETRY NOT NULL,
    Pharma_Adress VARCHAR2(100) NOT NULL,
    Phone_Number VARCHAR2(20) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Working_Hours VARCHAR2(100) NOT NULL
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Availability (
    InventoryID NUMBER PRIMARY KEY NOT NULL,
    DrugID NUMBER NOT NULL,
    PharmacyID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    Price NUMBER(10,2) NOT NULL,
    FOREIGN KEY (DrugID) REFERENCES Drugs(DrugID) ON DELETE CASCADE,
    FOREIGN KEY (PharmacyID) REFERENCES Institutions(PharmacyID) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Reservations (
    OrderID NUMBER PRIMARY KEY NOT NULL,
    UserID NUMBER NOT NULL,
    DrugID NUMBER NOT NULL,
    PharmacyID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    Order_Date DATE NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserId) ON DELETE CASCADE,
    FOREIGN KEY (DrugID) REFERENCES Drugs(DrugID) ON DELETE CASCADE,
    FOREIGN KEY (PharmacyID) REFERENCES Institutions(PharmacyID) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Reviews (
    ReviewID NUMBER PRIMARY KEY NOT NULL,
    UserID NUMBER NOT NULL,
    DrugID NUMBER NOT NULL,
    Content VARCHAR2(1000) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserId) ON DELETE CASCADE,
    FOREIGN KEY (DrugID) REFERENCES Drugs(DrugID) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Pharmacy_representatives (
    RepresentativeID NUMBER PRIMARY KEY NOT NULL,
    UserID NUMBER NOT NULL,
    PharmacyID NUMBER NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (PharmacyID) REFERENCES Institutions(PharmacyID) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Managers (
    ManagerID NUMBER PRIMARY KEY NOT NULL,
    UserID NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;

CREATE TABLE Favorites (
    FavoriteID NUMBER PRIMARY KEY NOT NULL,
    DrugID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    FOREIGN KEY (DrugID) REFERENCES Drugs(DrugID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserId) ON DELETE CASCADE
) TABLESPACE TS_MyPharmacy;